# Generated by Django 2.2 on 2022-11-05 18:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update_at')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='item name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='price')),
                ('number_count', models.PositiveIntegerField(default=0, verbose_name='number count')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_item', to='app_shops.ShopModel')),
            ],
            options={
                'verbose_name': 'sell_item',
                'verbose_name_plural': 'sell_items',
            },
        ),
    ]
