# Generated by Django 2.2 on 2022-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
