# Generated by Django 4.1.3 on 2022-11-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_auto_20221103_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='number_count',
            field=models.PositiveIntegerField(default=0, verbose_name='number count'),
        ),
    ]
